# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_person_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='author_headshots'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
